package io.fairyproject.gradle.resource.impl

import io.fairyproject.gradle.extension.FairyExtension
import io.fairyproject.gradle.platform.PlatformType
import io.fairyproject.gradle.resource.*
import org.gradle.api.Project
import java.util.*


class FairyResourceBukkitMeta: FairyResource {
    override fun generate(
        project: Project,
        fairyExtension: FairyExtension,
        classMapper: Map<ClassType, ClassInfo>
    ): ResourceInfo? {
        if (!fairyExtension.allPlatforms.contains(PlatformType.BUKKIT)) return null
        classMapper[ClassType.BUKKIT_PLUGIN] ?: return null
        val stringJoiner = StringJoiner("\n")

        stringJoiner.add("# Generated by Fairy")
        stringJoiner.add("name: ${project.name}")
        stringJoiner.add("version: ${project.version}")
        stringJoiner.add("description: ${project.description}");
        stringJoiner.add("main: ${classMapper[ClassType.BUKKIT_PLUGIN]!!.name.replace('/', '.')}")
        fairyExtension.bukkitProperties().forEach { key, value ->
            if (value is List<*>)
                stringJoiner.add("$key: [${value.joinToString(", ")}]")
            else
                stringJoiner.add("$key: $value")
        }

        return resourceOf("plugin.yml", stringJoiner.toString().encodeToByteArray())
    }
}