package io.fairyproject.gradle.resource.impl

import io.fairyproject.gradle.extension.FairyExtension
import io.fairyproject.gradle.resource.*
import org.gradle.api.Project
import java.util.*


class FairyResourceBukkitMeta: FairyResource {
    override fun generate(
        project: Project,
        fairyExtension: FairyExtension,
        classMapper: Map<ClassType, ClassInfo>
    ): ResourceInfo {
        val stringJoiner = StringJoiner("\n")

        stringJoiner.add("# Generated by Fairy")
        stringJoiner.add("name: " + project.name)
        stringJoiner.add("version: " + project.version)
        stringJoiner.add("main: " + classMapper.get(ClassType.BUKKIT_PLUGIN))
        stringJoiner.add("softdepend: [Fairy]")
        // TODO
//        if (extension.getDescription() != null) {
//            stringJoiner.add(extension.getDescription())
//        }
//        extension.properties(PlatformType.BUKKIT).forEach { k, v -> stringJoiner.add(k.toString() + ": " + v) }

        return resourceOf("plugin.yml", stringJoiner.toString().encodeToByteArray())
    }
}